export const SET_SINGER ='SET_SINGER'

export const SET_PLAYING_STATE = 'SET_PLAYING_STATE'

export const SET_FULL_SCREEN = 'SET_FULL_SCREEN'

export const SET_PLAYLIST = 'SET_PLAYLIST'

export const SET_SEQUENCE_LIST = 'SET_SEQUENCE_LIST'

export const SET_PLAY_MODE = 'SET_PLAY_MODE'

export const SET_CURRENT_INDEX = 'SET_CURRENT_INDEX'

export const SET_DISC = 'SET_DISC'

export const SET_SEARCH_HISTORY = 'SET_SEARCH_HISTORY'

export const SET_lOGIN_STATUS ='SET_lOGIN_STATUS'

export const SET_USER_INFO = 'SET_USER_INFO'
